# Lottery ticket 1
print ("Opening SNU_lottery.py")
print ("Reading script")
print ("Lines read: 0/124")
print ("Lines read: 115/124")
print ("Loading variables")
signinpasswordor = str("********")
print ("Importing modules")
import random
print ("Successfully imported the 'random' module")
print ("Checking numbers")
print ("Getting access to the database")
print ("Loaded!")
print (" ")
print ("Sign-in")
pass1 = int(random.randint(1,99))
pass2 = int(random.randint(1,99)) 
pass3 = int(random.randint(1,99))
pass4 = int(random.randint(1,99)) 
pass5 = int(random.randint(1,99))
pass6 = int(random.randint(1,99)) 
signinusername = input ("Enter your username: ")
signinpassword = input("Enter your password: ")
if signinpassword == signinpasswordor:
	print ("Welcome to the SNU lottery!")
	print (" ")
	print ("Here is today's mediapower reward:")
	print ("250,000,000,000,000 points")
	print ("500,000,000 SNU platinum")
	print ("2,250,000,000 SNU gold")
	print ("25,000,000,000 SNU silver")
	print ("750,000,000,000 SNU bronze")
	print ("$1000.00")
	print ("6000 ad skips")
	print ("500,000,000,000 XP")
	print (" ")
	print ("Lottery tickets are $0.001 each. You can buy them certain amounts at a time")
	print (" ")
	print ("| buy 1 ticket       | $0.001 | buy 150 tickets   | $0.150 | buy 2500 tickets  | $2.500  |")
	print ("| buy 5 tickets      | $0.001 | buy 200 tickets   | $0.200 | buy 5000 tickets  | $5.000  |")
	print ("| buy 10 tickets     | $0.010 | buy 250 tickets   | $0.250 | buy 10000 tickets | $10.000 |")
	print ("| buy 20 tickets     | $0.020 | buy 500 tickets   | $0.500 | buy 25000 tickets | $25.000 |")
	print ("| buy 50 tickets     | $0.050 | buy 1000 tickets  | $1.000 | buy 50000 tickets | $50.000 |")
	print ("| buy 100 tickets    | $0.100 | buy 2000 tickets  | $2.000 | buy 99999 tickets | $99.990 |")
	print ("Keep in mind, if you don't win, it isn't the end of the world. We will keep going until there are 20 winners")
	print ("Even if you don't make it, here are the default rewards:")
	print ("10 SNU gold")
	print ("5000 XP")
	print ("25000 points")
	print ("The current numbers for the latest jackpot are: 42 | 00 | 33 | 00 | 00 | 68 |")
	print (" ")
	print ("Insert a payment method to begin. Make sure that you have enough spare money. (TICKET LIMIT PER ACCOUNT: 10,000,000)")
	print (" ")
	print ("Payment method: Paypal")
	print ("Cart: 1 ticket | $0.001")
confirmpurchase1 = str(input("\nAre you sure you want to buy 1 SNU lottery ticket for $0.001? (y/n)"))
if confirmpurchase1 == ("y"):
	print ("Verifying purchase...")
pinenter = int(input("Please enter your 4 digit pin number"))
if pinenter == (1111) or (1234) or (4321) or (8888) or (9999):
	print ("Successfully Purchased 1 lottery ticket for $0.001!")
	print ("Your lottery ticket numbers") 
	slot1 = (pass1)
	slot2 = (pass1)
	slot3 = (pass1)
	slot4 = (pass1)
	slot5 = (pass1)
	slot6 = (pass1)
	print (slot1)
	print (slot2)
	print (slot3)
	print (slot4)
	print (slot5)
	print (slot6)
	print ("Winning numbers")
	print ("42")
	print ("0")
	print ("33")
	print ("0")
	print ("0")
	print ("68")
if (slot1 == 42) and (slot2 == 0) and (slot3 == 33) and (slot4 == 0) and (slot5 == 0) and (slot6 == 68):
	print ("You won the lottery!")
	print ("Reward:")
	print ("250,000,000,000,000 points")
	print ("500,000,000 SNU platinum")
	print ("2,250,000,000 SNU gold")
	print ("25,000,000,000 SNU silver")
	print ("750,000,000,000 SNU bronze")
	print ("$1000.00")
	print ("6000 ad skips")
	print ("500,000,000,000 XP")
	print ("Thank you for playing")
	print ("There are some rules in place though:")
	continue1 = input("press [ENTER] key to view the rules")
	print ("| LOTTERY WINNER RULES")
	print ("| You cannot sell your account. This will result in all your rewards being lost")
	print ("| This doesn't give you permission to put other people down. Each put-down that is spotted will remove 5% of your rewards")
	print ("| You cannot delete your account until all the rewards are given out")
	print ("| You have a limit of how much of your riches you can give out daily. You can only give up to 0.000010% per post, and only 0.25% total daily")
	print ("| ")
	print ("Thank you for participating in the SNU lottery! You got very lucky. ")
	print ("| Some recommendations:")
	print ("| upload some content, you will get a lot of attention")
	print ("| Share your lottery screenshot")
	print ("| Try not to spend too much on the first day, and only give SNU platinum, gold, and silver to posts you REALLY like. Even though you have so much, don't just give it to anyone, no matter how much they beg")
	print ("||||||||||||||||||||||")
	print ("| Your reward is now pending to make sure it wasn't botted")
	print ("| Check back in 2 hours to receive your reward if it was legitimate")
	print ("| If your number was illegitimate, you will be banned from participating in SNU lotteries for the next 4 years, and you will lose access to special features like:")
	print ("| * SNU platinum, gold, silver, and bronze")
	print ("| * creating new accounts")
	print ("| * boosts")
	print ("| Hopefully you didn't cheat")
	continue2 = input("Press [ENTER] key to continue back to SNU")
else:
	print ("You lost the lottery")
	print ("Better luck next time!")
final = input("Press enter to quit")
# one in a hundred billion tickets are winners
'''
limits are in place for how much of the reward people can give out daily
if the account is inactive for too long, the reward will get split 10000 ways between 10000 different high-level users
'''