# Sean Walla Walla offline
# Version 1.0 Build 1
# The offline version of the Sean Walla Walla website

print ("Welcome to the Sean Walla Walla offline terminal!")
print ("This is the offline version of the Sean Walla Walla website in terminal form. If you want a full GUI, try the HTML version")
print (" ")
print ("To start enter a username and password")
print (" ")
username1 = input("Username:")
password1 = input("Password:")
print (" ")
print ("Welcome back " + username1 + "!")
print (" ")
print ("Select a site interface to work with:")
print ("This terminal is using the September 7th 2018 snapshot")
print (" ")
print ("Sean Walla Walla Classic (contains # pages) ID = 1")
print ("SNU Classic (contains # pages) ID = 2")
interGui = int(input("Type in the code to enter the section"))
if interGui == 1:
	print ("Sean Walla Walla Classic")
	print ("Pages")
	print ("Home | ID = 1")
	classicsearch = int(input("Type in an ID to enter a page"))
	if classicsearch == 1:
		print ("HOME")
		print ("Sean Walla Walla August Logo.png")
		print ("------------------------------------")
		print (" ")
		print ("WELCOME")
		print (" ")
		print ("Welcome to the official Sean Walla Walla website! This website contains most content for our social media community and business")
		print (" ")
		print ("Renting a room at one of our apartments? GET PERSONALIZED SIGN-IN HERE")
		print (" ")
		print ("Check out SNU, our social media platform made for everything")
		print (" ")
		print ("Made for:")
		print (" ")
		print ("* Videos")
		print ("* Pictures")
		print ("* Music")
		print ("* Technology")
		print ("* Virtual machines")
		print (" ")
		print ("* Games")
		print ("* Comments")
		print ("* Reviews")
		print ("* Blogs")
		print ("* Parodies")
		print ("* Diversity")
		print ("* Literature")
		print (" ")
		print ("* News")
		print ("* Movies")
		print ("* Archival")
		print ("* Research")
		print ("* Hosting")
		print ("* Comics")
		print ("* Software")
		print (" ")
		print ("* Education")
		print ("* Adult videos")
		print ("* Petitions")
		print ("* Messaging")
		print ("* Support")
		print ("* Banks")
		print ("* Hotels")
		print (" ")
		print ("* Business")
		print ("* Delivery")
		print ("* Travel")
		print ("* Freedom")
		print ("* History")
		print ("* Photography")
		print ("* Forums")
		print (" ")
		print ("* Adverts")
		print ("* Jokes")
		print ("* memes")
		print ("* Animations")
		print ("* Kids")
		print ("* Software developers")
		print (" ")
		print ("And much more!")
		print (" ")
		print ("Portals")
		print (" ")
		print ("SFF")
		print ("Ringtones")
		print ("Holiday events")
		print ("Reviews")
		print ("Site news")
		print ("News")
		print ("Movie collection")
		print ("PNN (Positive News Network)")
		print ("SWWRC (Sean Walla Walla Repair Center")
		print (" ")
		print ("Getting started")
		print (" ")
		print ("To decrease lag on older machines (2001-2025) we have organized the pages on this site into 9 different categories (the news cateogyr stretches out through loads of pages")
		print ("1. Main (current)")
		print ("2. Residence (for our hotels and lofts)")
		print ("3. Community (where all our social media content is")
		print ("4. Software (downloads)")
		print ("5. Store (shopping)")
		print ("6. Services (for our online services - sign up and info)")
		print ("7. News and announcements (the sean walla walla news page)")
		print ("8. Seasonal")
		print ("9. Future news pages (changes daily)")
endin = input("Press ENTER to quit")
if endin == ("Enter"):
	print ("Goodbye")
else:
	print ("Goodbye")
